name: kiralayabilir_miyim
description: Kiralayabilir Miyim MVP Flutter app skeleton.
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  app_links: ^6.3.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21


